-- !Ups
CREATE TABLE "USERS" (
  "ID" UUID PRIMARY KEY,
  "EMAIL" VARCHAR(100) UNIQUE NOT NULL,
  "USERNAME" VARCHAR(50) UNIQUE NOT NULL,
  "PASSWORD" VARCHAR(255) NOT NULL,
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- !Downs
DROP TABLE IF EXISTS "USERS"
